SECRET_KEY: "\x85\x11\xFA\xEF\xF2A\x11\xC7\x90\x9C!{\xDC\x11W\xFB\x93\xE5\xA3\xCD\xE3\xC2\x9E#7\xC4\xCDa\xCF\xC9/\xEA"
JWT_ALGORITHM: HS256
DB_HOST: localhost
DB_NAME: DB_NAME
DB_USER: DB_NAME
DB_PORT: "3306"
DB_PASSWORD: OzcffFD9SL
